
services:
  aggregation-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-aggregation-server
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      # ログ出力用（オプション）
      - ./logs:/app/logs
    networks:
      - aggregation-network

    # ログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  aggregation-network:
    driver: bridge